package com.gfan.report.frame.module;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UiFwUserExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public UiFwUserExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    protected UiFwUserExample(UiFwUserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andLoginIdIsNull() {
            addCriterion("LOGIN_ID is null");
            return this;
        }

        public Criteria andLoginIdIsNotNull() {
            addCriterion("LOGIN_ID is not null");
            return this;
        }

        public Criteria andLoginIdEqualTo(String value) {
            addCriterion("LOGIN_ID =", value, "loginId");
            return this;
        }

        public Criteria andLoginIdNotEqualTo(String value) {
            addCriterion("LOGIN_ID <>", value, "loginId");
            return this;
        }

        public Criteria andLoginIdGreaterThan(String value) {
            addCriterion("LOGIN_ID >", value, "loginId");
            return this;
        }

        public Criteria andLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_ID >=", value, "loginId");
            return this;
        }

        public Criteria andLoginIdLessThan(String value) {
            addCriterion("LOGIN_ID <", value, "loginId");
            return this;
        }

        public Criteria andLoginIdLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_ID <=", value, "loginId");
            return this;
        }

        public Criteria andLoginIdLike(String value) {
            addCriterion("LOGIN_ID like", value, "loginId");
            return this;
        }

        public Criteria andLoginIdNotLike(String value) {
            addCriterion("LOGIN_ID not like", value, "loginId");
            return this;
        }

        public Criteria andLoginIdIn(List values) {
            addCriterion("LOGIN_ID in", values, "loginId");
            return this;
        }

        public Criteria andLoginIdNotIn(List values) {
            addCriterion("LOGIN_ID not in", values, "loginId");
            return this;
        }

        public Criteria andLoginIdBetween(String value1, String value2) {
            addCriterion("LOGIN_ID between", value1, value2, "loginId");
            return this;
        }

        public Criteria andLoginIdNotBetween(String value1, String value2) {
            addCriterion("LOGIN_ID not between", value1, value2, "loginId");
            return this;
        }

        public Criteria andCommerceIdIsNull() {
            addCriterion("COMMERCE_ID is null");
            return this;
        }

        public Criteria andCommerceIdIsNotNull() {
            addCriterion("COMMERCE_ID is not null");
            return this;
        }

        public Criteria andCommerceIdEqualTo(Integer value) {
            addCriterion("COMMERCE_ID =", value, "commerceId");
            return this;
        }

        public Criteria andCommerceIdNotEqualTo(Integer value) {
            addCriterion("COMMERCE_ID <>", value, "commerceId");
            return this;
        }

        public Criteria andCommerceIdGreaterThan(Integer value) {
            addCriterion("COMMERCE_ID >", value, "commerceId");
            return this;
        }

        public Criteria andCommerceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMMERCE_ID >=", value, "commerceId");
            return this;
        }

        public Criteria andCommerceIdLessThan(Integer value) {
            addCriterion("COMMERCE_ID <", value, "commerceId");
            return this;
        }

        public Criteria andCommerceIdLessThanOrEqualTo(Integer value) {
            addCriterion("COMMERCE_ID <=", value, "commerceId");
            return this;
        }

        public Criteria andCommerceIdIn(List values) {
            addCriterion("COMMERCE_ID in", values, "commerceId");
            return this;
        }

        public Criteria andCommerceIdNotIn(List values) {
            addCriterion("COMMERCE_ID not in", values, "commerceId");
            return this;
        }

        public Criteria andCommerceIdBetween(Integer value1, Integer value2) {
            addCriterion("COMMERCE_ID between", value1, value2, "commerceId");
            return this;
        }

        public Criteria andCommerceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("COMMERCE_ID not between", value1, value2, "commerceId");
            return this;
        }

        public Criteria andMediumIdIsNull() {
            addCriterion("MEDIUM_ID is null");
            return this;
        }

        public Criteria andMediumIdIsNotNull() {
            addCriterion("MEDIUM_ID is not null");
            return this;
        }

        public Criteria andMediumIdEqualTo(Integer value) {
            addCriterion("MEDIUM_ID =", value, "mediumId");
            return this;
        }

        public Criteria andMediumIdNotEqualTo(Integer value) {
            addCriterion("MEDIUM_ID <>", value, "mediumId");
            return this;
        }

        public Criteria andMediumIdGreaterThan(Integer value) {
            addCriterion("MEDIUM_ID >", value, "mediumId");
            return this;
        }

        public Criteria andMediumIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MEDIUM_ID >=", value, "mediumId");
            return this;
        }

        public Criteria andMediumIdLessThan(Integer value) {
            addCriterion("MEDIUM_ID <", value, "mediumId");
            return this;
        }

        public Criteria andMediumIdLessThanOrEqualTo(Integer value) {
            addCriterion("MEDIUM_ID <=", value, "mediumId");
            return this;
        }

        public Criteria andMediumIdIn(List values) {
            addCriterion("MEDIUM_ID in", values, "mediumId");
            return this;
        }

        public Criteria andMediumIdNotIn(List values) {
            addCriterion("MEDIUM_ID not in", values, "mediumId");
            return this;
        }

        public Criteria andMediumIdBetween(Integer value1, Integer value2) {
            addCriterion("MEDIUM_ID between", value1, value2, "mediumId");
            return this;
        }

        public Criteria andMediumIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MEDIUM_ID not between", value1, value2, "mediumId");
            return this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return this;
        }

        public Criteria andPasswordIn(List values) {
            addCriterion("PASSWORD in", values, "password");
            return this;
        }

        public Criteria andPasswordNotIn(List values) {
            addCriterion("PASSWORD not in", values, "password");
            return this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return this;
        }

        public Criteria andEmailAddressIsNull() {
            addCriterion("EMAIL_ADDRESS is null");
            return this;
        }

        public Criteria andEmailAddressIsNotNull() {
            addCriterion("EMAIL_ADDRESS is not null");
            return this;
        }

        public Criteria andEmailAddressEqualTo(String value) {
            addCriterion("EMAIL_ADDRESS =", value, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressNotEqualTo(String value) {
            addCriterion("EMAIL_ADDRESS <>", value, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressGreaterThan(String value) {
            addCriterion("EMAIL_ADDRESS >", value, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL_ADDRESS >=", value, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressLessThan(String value) {
            addCriterion("EMAIL_ADDRESS <", value, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressLessThanOrEqualTo(String value) {
            addCriterion("EMAIL_ADDRESS <=", value, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressLike(String value) {
            addCriterion("EMAIL_ADDRESS like", value, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressNotLike(String value) {
            addCriterion("EMAIL_ADDRESS not like", value, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressIn(List values) {
            addCriterion("EMAIL_ADDRESS in", values, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressNotIn(List values) {
            addCriterion("EMAIL_ADDRESS not in", values, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressBetween(String value1, String value2) {
            addCriterion("EMAIL_ADDRESS between", value1, value2, "emailAddress");
            return this;
        }

        public Criteria andEmailAddressNotBetween(String value1, String value2) {
            addCriterion("EMAIL_ADDRESS not between", value1, value2, "emailAddress");
            return this;
        }

        public Criteria andMobileNumberIsNull() {
            addCriterion("MOBILE_NUMBER is null");
            return this;
        }

        public Criteria andMobileNumberIsNotNull() {
            addCriterion("MOBILE_NUMBER is not null");
            return this;
        }

        public Criteria andMobileNumberEqualTo(Long value) {
            addCriterion("MOBILE_NUMBER =", value, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberNotEqualTo(Long value) {
            addCriterion("MOBILE_NUMBER <>", value, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberGreaterThan(Long value) {
            addCriterion("MOBILE_NUMBER >", value, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("MOBILE_NUMBER >=", value, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberLessThan(Long value) {
            addCriterion("MOBILE_NUMBER <", value, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberLessThanOrEqualTo(Long value) {
            addCriterion("MOBILE_NUMBER <=", value, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberIn(List values) {
            addCriterion("MOBILE_NUMBER in", values, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberNotIn(List values) {
            addCriterion("MOBILE_NUMBER not in", values, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberBetween(Long value1, Long value2) {
            addCriterion("MOBILE_NUMBER between", value1, value2, "mobileNumber");
            return this;
        }

        public Criteria andMobileNumberNotBetween(Long value1, Long value2) {
            addCriterion("MOBILE_NUMBER not between", value1, value2, "mobileNumber");
            return this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("COMPANY is null");
            return this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("COMPANY is not null");
            return this;
        }

        public Criteria andCompanyEqualTo(String value) {
            addCriterion("COMPANY =", value, "company");
            return this;
        }

        public Criteria andCompanyNotEqualTo(String value) {
            addCriterion("COMPANY <>", value, "company");
            return this;
        }

        public Criteria andCompanyGreaterThan(String value) {
            addCriterion("COMPANY >", value, "company");
            return this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY >=", value, "company");
            return this;
        }

        public Criteria andCompanyLessThan(String value) {
            addCriterion("COMPANY <", value, "company");
            return this;
        }

        public Criteria andCompanyLessThanOrEqualTo(String value) {
            addCriterion("COMPANY <=", value, "company");
            return this;
        }

        public Criteria andCompanyLike(String value) {
            addCriterion("COMPANY like", value, "company");
            return this;
        }

        public Criteria andCompanyNotLike(String value) {
            addCriterion("COMPANY not like", value, "company");
            return this;
        }

        public Criteria andCompanyIn(List values) {
            addCriterion("COMPANY in", values, "company");
            return this;
        }

        public Criteria andCompanyNotIn(List values) {
            addCriterion("COMPANY not in", values, "company");
            return this;
        }

        public Criteria andCompanyBetween(String value1, String value2) {
            addCriterion("COMPANY between", value1, value2, "company");
            return this;
        }

        public Criteria andCompanyNotBetween(String value1, String value2) {
            addCriterion("COMPANY not between", value1, value2, "company");
            return this;
        }

        public Criteria andDepartmentIdIsNull() {
            addCriterion("DEPARTMENT_ID is null");
            return this;
        }

        public Criteria andDepartmentIdIsNotNull() {
            addCriterion("DEPARTMENT_ID is not null");
            return this;
        }

        public Criteria andDepartmentIdEqualTo(String value) {
            addCriterion("DEPARTMENT_ID =", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdNotEqualTo(String value) {
            addCriterion("DEPARTMENT_ID <>", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdGreaterThan(String value) {
            addCriterion("DEPARTMENT_ID >", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEPARTMENT_ID >=", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdLessThan(String value) {
            addCriterion("DEPARTMENT_ID <", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdLessThanOrEqualTo(String value) {
            addCriterion("DEPARTMENT_ID <=", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdLike(String value) {
            addCriterion("DEPARTMENT_ID like", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdNotLike(String value) {
            addCriterion("DEPARTMENT_ID not like", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdIn(List values) {
            addCriterion("DEPARTMENT_ID in", values, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdNotIn(List values) {
            addCriterion("DEPARTMENT_ID not in", values, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdBetween(String value1, String value2) {
            addCriterion("DEPARTMENT_ID between", value1, value2, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdNotBetween(String value1, String value2) {
            addCriterion("DEPARTMENT_ID not between", value1, value2, "departmentId");
            return this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("ROLE_ID is null");
            return this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("ROLE_ID is not null");
            return this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("ROLE_ID =", value, "roleId");
            return this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("ROLE_ID <>", value, "roleId");
            return this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("ROLE_ID >", value, "roleId");
            return this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROLE_ID >=", value, "roleId");
            return this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("ROLE_ID <", value, "roleId");
            return this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("ROLE_ID <=", value, "roleId");
            return this;
        }

        public Criteria andRoleIdIn(List values) {
            addCriterion("ROLE_ID in", values, "roleId");
            return this;
        }

        public Criteria andRoleIdNotIn(List values) {
            addCriterion("ROLE_ID not in", values, "roleId");
            return this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_ID between", value1, value2, "roleId");
            return this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_ID not between", value1, value2, "roleId");
            return this;
        }

        public Criteria andProvinceIdIsNull() {
            addCriterion("PROVINCE_ID is null");
            return this;
        }

        public Criteria andProvinceIdIsNotNull() {
            addCriterion("PROVINCE_ID is not null");
            return this;
        }

        public Criteria andProvinceIdEqualTo(Integer value) {
            addCriterion("PROVINCE_ID =", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdNotEqualTo(Integer value) {
            addCriterion("PROVINCE_ID <>", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdGreaterThan(Integer value) {
            addCriterion("PROVINCE_ID >", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROVINCE_ID >=", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdLessThan(Integer value) {
            addCriterion("PROVINCE_ID <", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdLessThanOrEqualTo(Integer value) {
            addCriterion("PROVINCE_ID <=", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdIn(List values) {
            addCriterion("PROVINCE_ID in", values, "provinceId");
            return this;
        }

        public Criteria andProvinceIdNotIn(List values) {
            addCriterion("PROVINCE_ID not in", values, "provinceId");
            return this;
        }

        public Criteria andProvinceIdBetween(Integer value1, Integer value2) {
            addCriterion("PROVINCE_ID between", value1, value2, "provinceId");
            return this;
        }

        public Criteria andProvinceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PROVINCE_ID not between", value1, value2, "provinceId");
            return this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateIn(List values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateNotIn(List values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return this;
        }

        public Criteria andUpdateDateIn(List values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return this;
        }

        public Criteria andUpdateDateNotIn(List values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return this;
        }

        public Criteria andExpDateIsNull() {
            addCriterion("EXP_DATE is null");
            return this;
        }

        public Criteria andExpDateIsNotNull() {
            addCriterion("EXP_DATE is not null");
            return this;
        }

        public Criteria andExpDateEqualTo(Date value) {
            addCriterion("EXP_DATE =", value, "expDate");
            return this;
        }

        public Criteria andExpDateNotEqualTo(Date value) {
            addCriterion("EXP_DATE <>", value, "expDate");
            return this;
        }

        public Criteria andExpDateGreaterThan(Date value) {
            addCriterion("EXP_DATE >", value, "expDate");
            return this;
        }

        public Criteria andExpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EXP_DATE >=", value, "expDate");
            return this;
        }

        public Criteria andExpDateLessThan(Date value) {
            addCriterion("EXP_DATE <", value, "expDate");
            return this;
        }

        public Criteria andExpDateLessThanOrEqualTo(Date value) {
            addCriterion("EXP_DATE <=", value, "expDate");
            return this;
        }

        public Criteria andExpDateIn(List values) {
            addCriterion("EXP_DATE in", values, "expDate");
            return this;
        }

        public Criteria andExpDateNotIn(List values) {
            addCriterion("EXP_DATE not in", values, "expDate");
            return this;
        }

        public Criteria andExpDateBetween(Date value1, Date value2) {
            addCriterion("EXP_DATE between", value1, value2, "expDate");
            return this;
        }

        public Criteria andExpDateNotBetween(Date value1, Date value2) {
            addCriterion("EXP_DATE not between", value1, value2, "expDate");
            return this;
        }

        public Criteria andIfEnableIsNull() {
            addCriterion("IF_ENABLE is null");
            return this;
        }

        public Criteria andIfEnableIsNotNull() {
            addCriterion("IF_ENABLE is not null");
            return this;
        }

        public Criteria andIfEnableEqualTo(Short value) {
            addCriterion("IF_ENABLE =", value, "ifEnable");
            return this;
        }

        public Criteria andIfEnableNotEqualTo(Short value) {
            addCriterion("IF_ENABLE <>", value, "ifEnable");
            return this;
        }

        public Criteria andIfEnableGreaterThan(Short value) {
            addCriterion("IF_ENABLE >", value, "ifEnable");
            return this;
        }

        public Criteria andIfEnableGreaterThanOrEqualTo(Short value) {
            addCriterion("IF_ENABLE >=", value, "ifEnable");
            return this;
        }

        public Criteria andIfEnableLessThan(Short value) {
            addCriterion("IF_ENABLE <", value, "ifEnable");
            return this;
        }

        public Criteria andIfEnableLessThanOrEqualTo(Short value) {
            addCriterion("IF_ENABLE <=", value, "ifEnable");
            return this;
        }

        public Criteria andIfEnableIn(List values) {
            addCriterion("IF_ENABLE in", values, "ifEnable");
            return this;
        }

        public Criteria andIfEnableNotIn(List values) {
            addCriterion("IF_ENABLE not in", values, "ifEnable");
            return this;
        }

        public Criteria andIfEnableBetween(Short value1, Short value2) {
            addCriterion("IF_ENABLE between", value1, value2, "ifEnable");
            return this;
        }

        public Criteria andIfEnableNotBetween(Short value1, Short value2) {
            addCriterion("IF_ENABLE not between", value1, value2, "ifEnable");
            return this;
        }

        public Criteria andCreateUserLoginIdIsNull() {
            addCriterion("CREATE_USER_LOGIN_ID is null");
            return this;
        }

        public Criteria andCreateUserLoginIdIsNotNull() {
            addCriterion("CREATE_USER_LOGIN_ID is not null");
            return this;
        }

        public Criteria andCreateUserLoginIdEqualTo(String value) {
            addCriterion("CREATE_USER_LOGIN_ID =", value, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_LOGIN_ID <>", value, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdGreaterThan(String value) {
            addCriterion("CREATE_USER_LOGIN_ID >", value, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_LOGIN_ID >=", value, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdLessThan(String value) {
            addCriterion("CREATE_USER_LOGIN_ID <", value, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_LOGIN_ID <=", value, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdLike(String value) {
            addCriterion("CREATE_USER_LOGIN_ID like", value, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdNotLike(String value) {
            addCriterion("CREATE_USER_LOGIN_ID not like", value, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdIn(List values) {
            addCriterion("CREATE_USER_LOGIN_ID in", values, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdNotIn(List values) {
            addCriterion("CREATE_USER_LOGIN_ID not in", values, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_LOGIN_ID between", value1, value2, "createUserLoginId");
            return this;
        }

        public Criteria andCreateUserLoginIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_LOGIN_ID not between", value1, value2, "createUserLoginId");
            return this;
        }
    }
}