package com.gfan.report.frame.module;

import java.util.Date;

public class UiFwUser {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.NAME
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.LOGIN_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private String loginId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.COMMERCE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Integer commerceId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.MEDIUM_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Integer mediumId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.PASSWORD
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.EMAIL_ADDRESS
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private String emailAddress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.MOBILE_NUMBER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Long mobileNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.COMPANY
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private String company;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.DEPARTMENT_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private String departmentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.ROLE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Integer roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.PROVINCE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Integer provinceId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.CREATE_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.UPDATE_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.EXP_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Date expDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.IF_ENABLE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private Short ifEnable;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_USER.CREATE_USER_LOGIN_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private String createUserLoginId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.ID
     *
     * @return the value of UI_FW_USER.ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.ID
     *
     * @param id the value for UI_FW_USER.ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.NAME
     *
     * @return the value of UI_FW_USER.NAME
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.NAME
     *
     * @param name the value for UI_FW_USER.NAME
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.LOGIN_ID
     *
     * @return the value of UI_FW_USER.LOGIN_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.LOGIN_ID
     *
     * @param loginId the value for UI_FW_USER.LOGIN_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.COMMERCE_ID
     *
     * @return the value of UI_FW_USER.COMMERCE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Integer getCommerceId() {
        return commerceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.COMMERCE_ID
     *
     * @param commerceId the value for UI_FW_USER.COMMERCE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setCommerceId(Integer commerceId) {
        this.commerceId = commerceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.MEDIUM_ID
     *
     * @return the value of UI_FW_USER.MEDIUM_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Integer getMediumId() {
        return mediumId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.MEDIUM_ID
     *
     * @param mediumId the value for UI_FW_USER.MEDIUM_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setMediumId(Integer mediumId) {
        this.mediumId = mediumId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.PASSWORD
     *
     * @return the value of UI_FW_USER.PASSWORD
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.PASSWORD
     *
     * @param password the value for UI_FW_USER.PASSWORD
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.EMAIL_ADDRESS
     *
     * @return the value of UI_FW_USER.EMAIL_ADDRESS
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.EMAIL_ADDRESS
     *
     * @param emailAddress the value for UI_FW_USER.EMAIL_ADDRESS
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.MOBILE_NUMBER
     *
     * @return the value of UI_FW_USER.MOBILE_NUMBER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Long getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.MOBILE_NUMBER
     *
     * @param mobileNumber the value for UI_FW_USER.MOBILE_NUMBER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setMobileNumber(Long mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.COMPANY
     *
     * @return the value of UI_FW_USER.COMPANY
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.COMPANY
     *
     * @param company the value for UI_FW_USER.COMPANY
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.DEPARTMENT_ID
     *
     * @return the value of UI_FW_USER.DEPARTMENT_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.DEPARTMENT_ID
     *
     * @param departmentId the value for UI_FW_USER.DEPARTMENT_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.ROLE_ID
     *
     * @return the value of UI_FW_USER.ROLE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.ROLE_ID
     *
     * @param roleId the value for UI_FW_USER.ROLE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.PROVINCE_ID
     *
     * @return the value of UI_FW_USER.PROVINCE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.PROVINCE_ID
     *
     * @param provinceId the value for UI_FW_USER.PROVINCE_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.CREATE_DATE
     *
     * @return the value of UI_FW_USER.CREATE_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.CREATE_DATE
     *
     * @param createDate the value for UI_FW_USER.CREATE_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.UPDATE_DATE
     *
     * @return the value of UI_FW_USER.UPDATE_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.UPDATE_DATE
     *
     * @param updateDate the value for UI_FW_USER.UPDATE_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.EXP_DATE
     *
     * @return the value of UI_FW_USER.EXP_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.EXP_DATE
     *
     * @param expDate the value for UI_FW_USER.EXP_DATE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.IF_ENABLE
     *
     * @return the value of UI_FW_USER.IF_ENABLE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public Short getIfEnable() {
        return ifEnable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.IF_ENABLE
     *
     * @param ifEnable the value for UI_FW_USER.IF_ENABLE
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setIfEnable(Short ifEnable) {
        this.ifEnable = ifEnable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_USER.CREATE_USER_LOGIN_ID
     *
     * @return the value of UI_FW_USER.CREATE_USER_LOGIN_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public String getCreateUserLoginId() {
        return createUserLoginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_USER.CREATE_USER_LOGIN_ID
     *
     * @param createUserLoginId the value for UI_FW_USER.CREATE_USER_LOGIN_ID
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void setCreateUserLoginId(String createUserLoginId) {
        this.createUserLoginId = createUserLoginId;
    }
}