package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.UiFwUser;
import com.gfan.report.frame.module.UiFwUserExample;
import java.util.List;

public interface UiFwUserDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    int countByExample(UiFwUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    int deleteByExample(UiFwUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    void insert(UiFwUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    void insertSelective(UiFwUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    List selectByExample(UiFwUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    UiFwUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    int updateByExampleSelective(UiFwUser record, UiFwUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    int updateByExample(UiFwUser record, UiFwUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    int updateByPrimaryKeySelective(UiFwUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    int updateByPrimaryKey(UiFwUser record);
}