package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.UiFwUser;
import com.gfan.report.frame.module.UiFwUserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UiFwUserDAOImpl extends SqlMapClientDaoSupport implements UiFwUserDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public UiFwUserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public int countByExample(UiFwUserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("UI_FW_USER.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public int deleteByExample(UiFwUserExample example) {
        int rows = getSqlMapClientTemplate().delete("UI_FW_USER.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) {
        UiFwUser key = new UiFwUser();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("UI_FW_USER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void insert(UiFwUser record) {
        getSqlMapClientTemplate().insert("UI_FW_USER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public void insertSelective(UiFwUser record) {
        getSqlMapClientTemplate().insert("UI_FW_USER.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public List selectByExample(UiFwUserExample example) {
        List list = getSqlMapClientTemplate().queryForList("UI_FW_USER.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public UiFwUser selectByPrimaryKey(Integer id) {
        UiFwUser key = new UiFwUser();
        key.setId(id);
        UiFwUser record = (UiFwUser) getSqlMapClientTemplate().queryForObject("UI_FW_USER.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public int updateByExampleSelective(UiFwUser record, UiFwUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("UI_FW_USER.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public int updateByExample(UiFwUser record, UiFwUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("UI_FW_USER.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public int updateByPrimaryKeySelective(UiFwUser record) {
        int rows = getSqlMapClientTemplate().update("UI_FW_USER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    public int updateByPrimaryKey(UiFwUser record) {
        int rows = getSqlMapClientTemplate().update("UI_FW_USER.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table UI_FW_USER
     *
     * @ibatorgenerated Wed Sep 24 16:43:10 CST 2014
     */
    private static class UpdateByExampleParms extends UiFwUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, UiFwUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}